{
	"_Type": "Action.Type.ProgressBanner",
	"ActionResult": {
		"_Name": "ProgressBannerDescarga"
	},
	"ShowActivityIndicator": true,
	"Message": "Descargando..",
	"CompletionTimeout": 15,
	"Animated": true
}